// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8-wSb78lmpBUlEEHxn62dHjyrBHb1T64',
    appId: '1:114272095640:web:fee602ef330b64ab5e2fed',
    messagingSenderId: '114272095640',
    projectId: 'tripmate-4029c',
    authDomain: 'tripmate-4029c.firebaseapp.com',
    storageBucket: 'tripmate-4029c.appspot.com',
    measurementId: 'G-Z28YLJX0LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ZMOoBkPxmx9iDganHG1RJbudWuXMSes',
    appId: '1:114272095640:android:8caccda9c3b67d1e5e2fed',
    messagingSenderId: '114272095640',
    projectId: 'tripmate-4029c',
    storageBucket: 'tripmate-4029c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3SzDyBeQp5UiwZVAhkpebWa07zdcbro8',
    appId: '1:114272095640:ios:f5de41642be1d8d05e2fed',
    messagingSenderId: '114272095640',
    projectId: 'tripmate-4029c',
    storageBucket: 'tripmate-4029c.appspot.com',
    iosBundleId: 'com.example.assignmentTripmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3SzDyBeQp5UiwZVAhkpebWa07zdcbro8',
    appId: '1:114272095640:ios:f5de41642be1d8d05e2fed',
    messagingSenderId: '114272095640',
    projectId: 'tripmate-4029c',
    storageBucket: 'tripmate-4029c.appspot.com',
    iosBundleId: 'com.example.assignmentTripmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8-wSb78lmpBUlEEHxn62dHjyrBHb1T64',
    appId: '1:114272095640:web:963e177a62ec71b25e2fed',
    messagingSenderId: '114272095640',
    projectId: 'tripmate-4029c',
    authDomain: 'tripmate-4029c.firebaseapp.com',
    storageBucket: 'tripmate-4029c.appspot.com',
    measurementId: 'G-9TVBF98BB3',
  );
}
